<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Authors>Gurux Ltd</Authors>
        <Company>Gurux Ltd</Company>
        <Copyright>Copyright (c) 1998-2026 Gurux Ltd. All rights reserved.</Copyright>
        <PackageProjectUrl>www.gurux.fi/Gurux.Updater.Net</PackageProjectUrl>
        <Description>Gurux Data Relay Shared library.</Description>
        <Version Condition=" '$(BUILD_BUILDNUMBER)' == '' ">0.0.1-local</Version>
        <Version Condition=" '$(BUILD_BUILDNUMBER)' != '' ">$(BUILD_BUILDNUMBER)</Version>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>GPL-2.0-only</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Gurux/Gurux.Data.Relay</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
        <PackageReference Include="Gurux.Scheduling" Version="1.0.2609.2201" />
        <PackageReference Include="Gurux.Service.Common" Version="3.0.2609.2901" />
        <SupportedPlatform Include="browser" />
    </ItemGroup>
</Project>
